import { convert } from 'pandoc-wasm';

self.onmessage = async (event) => {
  const { type, payload } = event.data;

  try {
    if (type === 'INIT') {
      // The new pandoc-wasm API doesn't need an explicit init() call
      // We just notify success to unlock the UI
      self.postMessage({ type: 'INIT_SUCCESS' });
    } else if (type === 'CONVERT') {
      const { text, inputFormat, outputFormat } = payload;
      
      const options = {
        from: inputFormat,
        to: outputFormat,
        standalone: true
      };

      const result = await convert(options, text, {});
      
      if (result.stderr) {
        console.warn('Pandoc stderr:', result.stderr);
      }
      
      self.postMessage({ type: 'CONVERT_SUCCESS', result: result.stdout });
    } else if (type === 'CONVERT_FILE') {
      const { fileData, fileName, inputFormat, outputFormat } = payload;
      
      const virtualFileName = `input.${inputFormat}`;
      const virtualOutputName = `output.${outputFormat}`;
      
      // Use Blob to pass binary data to pandoc-wasm virtual FS
      const blob = new Blob([fileData]);
      const files = {
        [virtualFileName]: blob
      };

      const options = {
        from: inputFormat,
        to: outputFormat,
        standalone: true,
        'input-files': [virtualFileName]
      };

      // If the target is a binary format (docx, epub), we must instruct Pandoc 
      // to write to a virtual output file instead of stdout
      const isBinaryOutput = ['docx', 'epub'].includes(outputFormat);
      if (isBinaryOutput) {
        options['output-file'] = virtualOutputName;
      }

      // 1st param: options
      // 2nd param: stdin (null because we are reading from virtual file)
      // 3rd param: files object
      const result = await convert(options, null, files);
      
      if (result.stderr) {
        console.warn('Pandoc stderr:', result.stderr);
      }

      if (isBinaryOutput) {
        const outputBlob = result.files[virtualOutputName];
        if (!outputBlob) {
          throw new Error('Binary output file was not generated by Pandoc.');
        }
        // Send ArrayBuffer back to main thread
        const arrayBuffer = await outputBlob.arrayBuffer();
        self.postMessage({ 
          type: 'CONVERT_FILE_SUCCESS', 
          result: arrayBuffer, 
          isBinary: true 
        });
      } else {
        self.postMessage({ 
          type: 'CONVERT_FILE_SUCCESS', 
          result: result.stdout, 
          isBinary: false 
        });
      }
    }
  } catch (error: any) {
    self.postMessage({ type: 'ERROR', error: error.message || 'Pandoc WASM Error' });
  }
};
