import { convert } from 'pandoc-wasm';

self.onmessage = async (event) => {
  const { type, payload } = event.data;

  try {
    if (type === 'INIT') {
      self.postMessage({ type: 'INIT_SUCCESS' });
    } else if (type === 'CONVERT') {
      const { text, fileData, inputFormat, outputFormat } = payload;
      
      const targetFormat = outputFormat === 'pdf' ? 'html' : outputFormat;
      const isBinaryInput = !!fileData;
      const isBinaryOutput = ['docx', 'epub'].includes(targetFormat);
      
      const virtualOutputName = `output.${targetFormat}`;
      const virtualInputName = `input.${inputFormat}`;

      const options: any = {
        from: inputFormat,
        to: targetFormat,
        standalone: true
      };

      const files: Record<string, any> = {};
      let stdin: string | null = null;
      
      if (isBinaryInput) {
        files[virtualInputName] = new Blob([fileData]);
        options['input-files'] = [virtualInputName];
      } else {
        stdin = text;
      }

      if (isBinaryOutput) {
        options['output-file'] = virtualOutputName;
      }

      const result = await convert(options, stdin, files);
      
      if (result.stderr) {
        console.warn('Pandoc stderr:', result.stderr);
      }

      if (isBinaryOutput) {
        const outputBlob = result.files[virtualOutputName];
        if (!outputBlob) {
          throw new Error('Binary output file was not generated by Pandoc.');
        }
        const arrayBuffer = await outputBlob.arrayBuffer();
        self.postMessage({ 
          type: 'CONVERT_SUCCESS', 
          result: arrayBuffer, 
          isBinary: true 
        });
      } else {
        self.postMessage({ 
          type: 'CONVERT_SUCCESS', 
          result: result.stdout, 
          isBinary: false 
        });
      }
    }
  } catch (error: any) {
    self.postMessage({ type: 'ERROR', error: error.message || 'Pandoc WASM Error' });
  }
};
